/**
 * AUDIT-222 status -> frozen ruleId attribution map (GENERATED once, then FROZEN).
 *
 * Used ONLY by the one-time backfill (backfillGapRuleIds.ts) to attribute historical therapy_gaps
 * rows, which carry a status string but no ruleId. The LIVE write path does NOT use this map - it
 * reads DetectedGap.ruleId directly, so a status rename never moves an id.
 *
 * Do NOT regenerate this map to "resync" it with renamed statuses. Its job is to describe status text
 * as it was STORED. If a status changes, the OLD text must remain here (pointing at the same frozen
 * ruleId) or historical rows carrying it become orphans. Ids change only via a documented data
 * migration on therapy_gaps.ruleId - see docs/audit/AUDIT_222_223_JOINT_DESIGN.md section 3.
 *
 * DRIFT-44 EXCEPTION (deliberate, documented): the KEYS below are byte-exact copies of status strings the
 * engine emits, and two of them contain non-ASCII characters that the engine itself uses - an em-dash in
 * the WPW/AF safety status and a '<=' sign in the iron-deficiency status. They are DATA, not authored
 * prose: normalising them to ASCII would make the key stop matching the stored status and silently break
 * attribution for those rows. Verbatim fidelity wins; do not "fix" these characters.
 */

/** Exact literal status -> frozen ruleId (one entry per literal gaps.push status in the engine). */
export const RULE_ID_BY_STATUS: Readonly<Record<string, string>> = Object.freeze({
  '3D echocardiography recommended for review for structural intervention planning': 'slug:3d-echocardiography-recommended-for-review-for-structural-intervention',
  'ABI screening not performed': 'gap-pv-2-abi-screening',
  'ACEi/ARB not prescribed in PAD with hypertension': 'gap-pv-11-acei-pad',
  'ACEi/ARB not prescribed post-MI': 'gap-cad-acei',
  'ACEi/ARB/ARNi not prescribed in HFrEF': 'slug:acei-arb-arni-not-prescribed-in-hfref',
  'AF ablation not referred in HFrEF (CASTLE-AF)': 'gap-ep-014-af-ablation-hfref',
  'ARVC with ventricular tachycardia - ICD evaluation': 'gap-hf-074-arvc-icd',
  'ATTR cardiac amyloidosis without disease-modifying therapy': 'gap-hf-054-attr-dmt',
  'ATTR-CM screening recommended for review': 'slug:attr-cm-screening-recommended-for-review',
  'AVR not referred for asymptomatic severe AS with LV dysfunction (Class IIa)': 'gap-sh-006-asymptomatic-as',
  'AVR not referred for severe symptomatic aortic stenosis': 'gap-sh-2-tavr-eval',
  'Abdominal aortic aneurysm screening recommended for review': 'gap-pv-9-aaa-screening',
  'Abnormal ABI (<=0.90) without a coded PAD diagnosis: undiagnosed peripheral artery disease': 'gap-pv-003-abnormal-abi',
  'Absolute iron deficiency untreated in heart failure': 'gap-hf-033-iron-def-iv',
  'Acute myocarditis follow-up recommended for review': 'slug:acute-myocarditis-follow-up-recommended-for-review',
  'Adult Tetralogy of Fallot: pulmonary valve replacement evaluation gap': 'gap-sh-11-tmvr',
  'Adult congenital heart disease specialist referral recommended for review': 'slug:adult-congenital-heart-disease-specialist-referral-recommended-for-rev',
  'Advanced CKD without heart-failure screening (cardiorenal type 4)': 'gap-hf-139-crs4-screen',
  'Alcohol septal ablation candidacy recommended for review in symptomatic HCM': 'gap-sh-15-alcohol-septal',
  'Amiodarone toxicity monitoring recommended for review': 'gap-ep-amiodarone-monitor',
  'Amyloid biomarker follow-up overdue (no recent BNP/NT-proBNP)': 'gap-hf-90-amyloid-biomarker',
  'Annual comprehensive foot exam recommended for review in PAD with diabetes': 'gap-pv-14-foot-exam',
  'Anticoagulation gap in cardiac amyloidosis with atrial fibrillation': 'gap-hf-077-amyloid-af-oac',
  'Anticoagulation not continued after AF ablation': 'gap-ep-071-post-ablation-oac',
  'Anticoagulation/antiplatelet not documented in early post-bioprosthetic valve period': 'slug:anticoagulation-antiplatelet-not-documented-in-early-post-bioprostheti',
  'Antiplatelet therapy missing in PAD': 'gap-pv-3-antiplatelet',
  'Aortic regurgitation without surveillance echo on file': 'gap-vhd-102-ar-surveillance',
  'Aortic root dilation monitoring recommended for review': 'slug:aortic-root-dilation-monitoring-recommended-for-review',
  'Apixaban dose reduction criteria met but on full dose': 'gap-ep-004-apixaban-underdose-criteria',
  'Apixaban inappropriately reduced without criteria': 'gap-ep-005-apixaban-inappropriate-underdose',
  'Behcet vascular thrombosis without immunosuppression: inflammatory thrombosis needs disease control': 'gap-pv-042-behcet-vascular',
  'Benign cardiac neoplasm (atrial myxoma): surgical referral gap': 'gap-sh-103-atrial-myxoma',
  'Beta-blocker not prescribed in Long QT syndrome': 'gap-ep-lqts-bb',
  'Beta-blocker not prescribed post-MI with reduced LVEF': 'gap-cad-bb-post-mi',
  'Bioprosthetic valve degeneration monitoring recommended for review': 'slug:bioprosthetic-valve-degeneration-monitoring-recommended-for-review',
  'Bioprosthetic valve with elevated gradient: structural deterioration (SVD) evaluation gap': 'gap-vhd-011-bio-svd-gradient',
  'Blood pressure monitoring recommended for review in CAD patient': 'slug:blood-pressure-monitoring-recommended-for-review-in-cad-patient',
  'Bradycardia on AV-nodal blocker: reduce drug before pacemaker decision': 'gap-ep-030-brady-avn-blocker-reduce',
  'Buerger disease with continued tobacco use: complete cessation is disease-modifying': 'gap-pv-041-buerger-cessation',
  'CIED infection/complication - lead extraction evaluation': 'gap-hf-031-lead-extraction',
  'CRITICAL: AV nodal blocker contraindicated in pre-excited AF (WPW + AF) — risk of ventricular fibrillation': 'gap-ep-079-wpw-af-avn-blocker',
  'CRT-D upgrade evaluation recommended for review': 'gap-hf-86-crt-d-upgrade',
  'CTEPH without riociguat: PH-specific therapy gap (operability review)': 'gap-pv-081-cteph-riociguat',
  'CTI ablation not offered for typical atrial flutter': 'gap-ep-074-flutter-cti-ablation',
  'Cardiac MRI not documented for non-ischemic cardiomyopathy': 'gap-hf-75-cardiac-mri',
  'Cardiac contractility modulation (CCM/Optimizer) candidacy': 'gap-hf-126-ccm-candidate',
  'Cardiac rehabilitation referral not documented for HF': 'gap-hf-20-cardiac-rehab',
  'Cardiac sarcoidosis screening recommended for review': 'slug:cardiac-sarcoidosis-screening-recommended-for-review',
  'Cardiac sarcoidosis without immunosuppressive therapy': 'gap-hf-063-sarcoid-immunosupp',
  'Cardiac transplant evaluation referral recommended for review': 'gap-hf-84-transplant-eval',
  'Cardio-oncology evaluation not documented in HF with cancer': 'gap-hf-80-cardio-oncology',
  'CardioMEMS PA-pressure monitor candidacy (NYHA III + elevated natriuretic peptide)': 'gap-hf-027-cardiomems',
  'Carotid screening recommended for review in PAD with stroke risk factors': 'gap-pv-13-carotid',
  'Chronic AF with HR<40 on rate control: adjust medication vs pacing': 'gap-ep-033-af-slow-rate-pacing',
  'Chronic ergot-alkaloid therapy: drug-induced valve disease surveillance echo gap': 'gap-vhd-092-ergot-alkaloid-valve-surveillance',
  'Cilostazol not prescribed for claudication in PAD': 'gap-pv-10-cilostazol',
  'Coarctation of the aorta without serial imaging surveillance': 'gap-sh-095-coarctation-surveillance',
  'Colchicine not prescribed in pericarditis': 'gap-hf-143-pericarditis-colch',
  'Complicated type-B aortic dissection (malperfusion): urgent TEVAR evaluation gap': 'gap-sh-075-typeb-tevar',
  'Compression therapy assessment recommended for review in venous disease with edema': 'gap-pv-15-compression',
  'Consider A1c target review for CAD patient with diabetes and elevated A1c': 'slug:consider-a1c-target-review-for-cad-patient-with-diabetes-and-elevated',
  'Consider ACEi/ARB for stable CAD with hypertension': 'slug:consider-acei-arb-for-stable-cad-with-hypertension',
  'Consider ACEi/ARB to ARNi switch evaluation for HFrEF': 'gap-hf-arni-switch',
  'Consider AFib catheter ablation referral (symptomatic AF on antiarrhythmic)': 'gap-ep-ablation',
  'Consider ARVC evaluation in young patient with cardiomyopathy and ventricular tachycardia': 'slug:consider-arvc-evaluation-in-young-patient-with-cardiomyopathy-and-vent',
  'Consider Brugada syndrome screening in young patient with unexplained syncope': 'gap-ep-brugada',
  'Consider CCTA for evaluation of stable chest pain': 'gap-cad-cardiac-ct',
  'Consider CRT evaluation for LVEF <=35% with wide QRS': 'gap-ep-device-crt',
  'Consider DAPT duration review: assess continued need beyond 12 months': 'gap-cad-dapt-duration',
  'Consider DVT screening for unilateral edema': 'gap-pv-dvt-screen',
  'Consider EP study for WPW syndrome risk stratification': 'gap-ep-wpw',
  'Consider GLP-1 RA for cardiovascular risk reduction in CAD + diabetes': 'slug:consider-glp-1-ra-for-cardiovascular-risk-reduction-in-cad-diabetes',
  'Consider ICD evaluation for primary prevention in HFrEF': 'slug:consider-icd-evaluation-for-primary-prevention-in-hfref',
  'Consider ICD programming optimization review': 'slug:consider-icd-programming-optimization-review',
  'Consider ICD programming review for inappropriate shock prevention in AF patient': 'gap-ep-inappropriate-shocks',
  'Consider IV iron therapy monitoring with follow-up ferritin and TSAT': 'slug:consider-iv-iron-therapy-monitoring-with-follow-up-ferritin-and-tsat',
  'Consider LAAC device evaluation for AFib with OAC contraindication': 'gap-ep-laac',
  'Consider LV non-compaction evaluation in young patient with unexplained cardiomyopathy': 'gap-hf-lvnc',
  'Consider Lipoprotein(a) screening in premature ASCVD': 'gap-cad-lpa',
  'Consider MINOCA comprehensive workup for MI with non-obstructive coronaries': 'gap-cad-minoca',
  'Consider MRA for post-MI patient with LVEF<=40% and HF': 'slug:consider-mra-for-post-mi-patient-with-lvef-40-and-hf',
  'Consider MRI-conditional status documentation for cardiac implantable device': 'gap-ep-cied-mri',
  'Consider PPI for GI protection in CAD patient on DAPT with GI risk factors': 'slug:consider-ppi-for-gi-protection-in-cad-patient-on-dapt-with-gi-risk-fac',
  'Consider PRN nitroglycerin for angina symptom relief': 'slug:consider-prn-nitroglycerin-for-angina-symptom-relief',
  'Consider PVC-induced cardiomyopathy evaluation': 'slug:consider-pvc-induced-cardiomyopathy-evaluation',
  'Consider Ross procedure candidacy evaluation for young patient with severe AS': 'slug:consider-ross-procedure-candidacy-evaluation-for-young-patient-with-se',
  'Consider SCAD evaluation for young female MI without atherosclerotic CAD': 'gap-cad-scad',
  'Consider SGLT2i for cardiovascular risk reduction in CAD + diabetes': 'gap-cad-sglt2-dm',
  'Consider TEE before cardioversion in AF without adequate anticoagulation': 'slug:consider-tee-before-cardioversion-in-af-without-adequate-anticoagulati',
  'Consider Takotsubo syndrome follow-up and recovery monitoring': 'slug:consider-takotsubo-syndrome-follow-up-and-recovery-monitoring',
  'Consider VSD closure evaluation for ventricular septal defect': 'slug:consider-vsd-closure-evaluation-for-ventricular-septal-defect',
  'Consider VT ablation referral for recurrent ventricular tachycardia with ICD shocks': 'gap-ep-vt-ablation',
  'Consider VTE anticoagulation duration review and continued need assessment': 'gap-pv-anticoag-vte',
  'Consider a potent P2Y12 inhibitor (ticagrelor or prasugrel) for ACS': 'gap-cad-ticagrelor-acs',
  'Consider advance care planning discussion for advanced heart failure': 'slug:consider-advance-care-planning-discussion-for-advanced-heart-failure',
  'Consider annual CHA2DS2-VASc score reassessment for AF patient on anticoagulation': 'slug:consider-annual-cha2ds2-vasc-score-reassessment-for-af-patient-on-anti',
  'Consider antiarrhythmic drug review post-ablation': 'slug:consider-antiarrhythmic-drug-review-post-ablation',
  'Consider anticoagulation bridging assessment for CAD+AF patient with upcoming procedure': 'slug:consider-anticoagulation-bridging-assessment-for-cad-af-patient-with-u',
  'Consider anticoagulation reversal emergency plan documentation for mechanical valve': 'slug:consider-anticoagulation-reversal-emergency-plan-documentation-for-mec',
  'Consider antiplatelet duration review for long-term DAPT post MI': 'slug:consider-antiplatelet-duration-review-for-long-term-dapt-post-mi',
  'Consider aortic surveillance for bicuspid valve-associated aortopathy': 'slug:consider-aortic-surveillance-for-bicuspid-valve-associated-aortopathy',
  'Consider arrhythmia screening in adult congenital heart disease': 'slug:consider-arrhythmia-screening-in-adult-congenital-heart-disease',
  'Consider aspirin therapy assessment for established CAD': 'slug:consider-aspirin-therapy-assessment-for-established-cad',
  'Consider bempedoic acid for statin-intolerant CAD patient with elevated LDL': 'gap-cad-bempedoic',
  'Consider beta-blocker assessment for stable CAD': 'gap-cad-beta-blocker',
  'Consider calcium channel blocker for Raynaud phenomenon': 'gap-pv-raynaud',
  'Consider calcium channel blocker for vasospastic angina': 'gap-cad-vasospastic',
  'Consider carcinoid valve disease screening and surveillance': 'slug:consider-carcinoid-valve-disease-screening-and-surveillance',
  'Consider cardiac allograft vasculopathy (CAV) surveillance in heart transplant recipient': 'gap-cad-cardiac-transplant-cad',
  'Consider cardiac catheterization review for high-risk CAD features': 'gap-cad-catheterization',
  'Consider cardiac sarcoidosis arrhythmia evaluation': 'slug:consider-cardiac-sarcoidosis-arrhythmia-evaluation',
  'Consider cardioversion timing assessment for atrial fibrillation': 'slug:consider-cardioversion-timing-assessment-for-atrial-fibrillation',
  'Consider catheter ablation referral for recurrent supraventricular tachycardia': 'gap-ep-svt-ablation',
  'Consider catheter ablation timing optimization for AF on antiarrhythmic therapy': 'slug:consider-catheter-ablation-timing-optimization-for-af-on-antiarrhythmi',
  'Consider chest pain protocol adherence review with troponin assessment': 'gap-cad-chest-pain-protocol',
  'Consider clopidogrel as alternative antiplatelet for PAD with aspirin intolerance': 'slug:consider-clopidogrel-as-alternative-antiplatelet-for-pad-with-aspirin',
  'Consider coarctation surveillance and hypertension management': 'gap-sh-coarctation',
  'Consider complete revascularization assessment for multivessel CAD': 'gap-cad-complete-revasc',
  'Consider comprehensive Fontan surveillance evaluation': 'gap-sh-fontan-surveillance',
  'Consider comprehensive decongestive therapy referral for lymphedema': 'gap-pv-lymphedema',
  'Consider comprehensive secondary prevention bundle review for CAD': 'gap-cad-secondary-prevention',
  'Consider comprehensive venous ulcer management protocol': 'slug:consider-comprehensive-venous-ulcer-management-protocol',
  'Consider compression therapy for post-thrombotic syndrome prevention after DVT': 'gap-pv-pts-prevention',
  'Consider conduction system pacing evaluation': 'gap-ep-csp',
  'Consider coronary CTA follow-up imaging interval review': 'slug:consider-coronary-cta-follow-up-imaging-interval-review',
  'Consider coronary artery calcium scoring for intermediate-risk patient': 'gap-cad-calcium-score',
  'Consider diuretic dose optimization for persistent congestion in HF': 'slug:consider-diuretic-dose-optimization-for-persistent-congestion-in-hf',
  'Consider early rhythm control strategy evaluation for atrial fibrillation': 'gap-ep-early-rhythm',
  'Consider echocardiographic surveillance for bicuspid aortic valve': 'gap-sh-bicuspid-surveillance',
  'Consider echocardiography for LVEF assessment in CAD': 'slug:consider-echocardiography-for-lvef-assessment-in-cad',
  'Consider endovascular intervention evaluation for lifestyle-limiting claudication': 'slug:consider-endovascular-intervention-evaluation-for-lifestyle-limiting-c',
  'Consider exercise stress testing for arrhythmia characterization': 'slug:consider-exercise-stress-testing-for-arrhythmia-characterization',
  'Consider extended workup for young MI (age <45) including thrombophilia and substance screening': 'slug:consider-extended-workup-for-young-mi-age-45-including-thrombophilia-a',
  'Consider fibromuscular dysplasia screening in young woman with early-onset hypertension': 'gap-pv-034-fmd-screening',
  'Consider finerenone in HFmrEF/HFpEF (FINEARTS-HF)': 'gap-hf-017-finerenone-mref',
  'Consider formal CHA2DS2-VASc score documentation for AF stroke risk stratification': 'slug:consider-formal-cha2ds2-vasc-score-documentation-for-af-stroke-risk-st',
  'Consider generator replacement planning review for aging CIED patient': 'slug:consider-generator-replacement-planning-review-for-aging-cied-patient',
  'Consider glucose screening for CAD patient without known diabetes': 'slug:consider-glucose-screening-for-cad-patient-without-known-diabetes',
  'Consider hemodynamic assessment review for HF with elevated BNP': 'slug:consider-hemodynamic-assessment-review-for-hf-with-elevated-bnp',
  'Consider hemoglobin assessment for post-MI patient': 'slug:consider-hemoglobin-assessment-for-post-mi-patient',
  'Consider icosapent ethyl for elevated triglycerides in CAD': 'gap-cad-omega3',
  'Consider infective endocarditis evaluation for prosthetic valve patient with fever': 'slug:consider-infective-endocarditis-evaluation-for-prosthetic-valve-patien',
  'Consider interval duplex surveillance for peripheral bypass graft': 'gap-pv-graft-surveillance',
  'Consider ivabradine for inappropriate sinus tachycardia': 'slug:consider-ivabradine-for-inappropriate-sinus-tachycardia',
  'Consider lead integrity assessment for aging ICD system': 'gap-ep-lead-integrity',
  'Consider left atrial size documentation for AF management planning': 'slug:consider-left-atrial-size-documentation-for-af-management-planning',
  'Consider lipid panel follow-up for CAD patient on statin therapy': 'gap-cad-lipid-panel-fu',
  'Consider low-dose aspirin for bioprosthetic valve >3 months post-implant': 'gap-vd-antiplatelet-bioprosthetic',
  'Consider low-dose colchicine for residual inflammatory risk in CAD': 'gap-cad-colchicine',
  'Consider low-dose rivaroxaban + aspirin per COMPASS trial for PAD': 'gap-pv-rivaroxaban',
  'Consider maintenance exercise prescription for CAD patient post cardiac rehabilitation': 'slug:consider-maintenance-exercise-prescription-for-cad-patient-post-cardia',
  'Consider mesenteric ischemia evaluation in PAD patient with intestinal vascular symptoms': 'gap-pv-mesenteric',
  'Consider microvascular disease assessment for angina with non-obstructive coronaries': 'gap-cad-microvascular',
  'Consider multidisciplinary valve clinic referral for symptomatic valve disease': 'slug:consider-multidisciplinary-valve-clinic-referral-for-symptomatic-valve',
  'Consider naftidrofuryl for severe claudication per ESC/ESVS Guideline': 'slug:consider-naftidrofuryl-for-severe-claudication-per-esc-esvs-guideline',
  'Consider nuclear stress test for intermediate-risk CAD patient': 'slug:consider-nuclear-stress-test-for-intermediate-risk-cad-patient',
  'Consider oral anticoagulation in CAD patient with atrial fibrillation': 'gap-cad-anticoag-af',
  'Consider pacemaker upgrade to CRT evaluation': 'gap-ep-pacemaker-upgrade',
  'Consider pannus vs thrombosis evaluation for prosthetic valve with new symptoms': 'slug:consider-pannus-vs-thrombosis-evaluation-for-prosthetic-valve-with-new',
  'Consider pentoxifylline for claudication in PAD patient with HF (cilostazol contraindicated)': 'slug:consider-pentoxifylline-for-claudication-in-pad-patient-with-hf-cilost',
  'Consider pill-in-pocket strategy for paroxysmal AF without structural heart disease': 'slug:consider-pill-in-pocket-strategy-for-paroxysmal-af-without-structural',
  'Consider potassium monitoring for HF patient on mineralocorticoid receptor antagonist': 'gap-hf-potassium-monitor',
  'Consider potassium monitoring for post-MI patient on diuretic': 'slug:consider-potassium-monitoring-for-post-mi-patient-on-diuretic',
  'Consider prasugrel for ACS with PCI per TRITON-TIMI 38 evidence': 'gap-cad-prasugrel',
  'Consider pulsed field ablation candidacy evaluation': 'gap-ep-pfa',
  'Consider radiation-associated valve disease evaluation': 'gap-vd-radiation-valve',
  'Consider ranolazine for refractory angina on maximal anti-anginal therapy': 'gap-cad-ranolazine',
  'Consider remote monitoring enrollment for cardiac implantable device': 'slug:consider-remote-monitoring-enrollment-for-cardiac-implantable-device',
  'Consider renal function monitoring for CAD patient on ACEi/ARB': 'gap-cad-renal-monitor',
  'Consider revascularization assessment for multivessel CAD with reduced LVEF': 'gap-cad-revascularization',
  'Consider right heart catheterization for valve disease with pulmonary hypertension': 'slug:consider-right-heart-catheterization-for-valve-disease-with-pulmonary',
  'Consider secondary prevention ICD evaluation for cardiac arrest survivor': 'slug:consider-secondary-prevention-icd-evaluation-for-cardiac-arrest-surviv',
  'Consider secondary tricuspid regurgitation assessment in left heart disease': 'gap-vd-tricuspid-secondary',
  'Consider sleep apnea screening for CAD patient with obesity': 'slug:consider-sleep-apnea-screening-for-cad-patient-with-obesity',
  'Consider structured weight management program for CAD patient with obesity': 'slug:consider-structured-weight-management-program-for-cad-patient-with-obe',
  'Consider subclinical AF screening via device interrogation': 'gap-ep-subclinical-af',
  'Consider supervised exercise rehabilitation post vascular intervention': 'slug:consider-supervised-exercise-rehabilitation-post-vascular-intervention',
  'Consider surgical bypass evaluation for chronic limb-threatening ischemia': 'gap-pv-bypass-eval',
  'Consider syncope workup evaluation': 'gap-ep-syncope',
  'Consider thiamine supplementation for HF patient on loop diuretics with malnutrition': 'slug:consider-thiamine-supplementation-for-hf-patient-on-loop-diuretics-wit',
  'Consider thoracic outlet syndrome evaluation for young patient with upper extremity vascular symptoms': 'gap-pv-thoracic-outlet',
  'Consider thyroid function testing in CAD patient with atrial fibrillation': 'slug:consider-thyroid-function-testing-in-cad-patient-with-atrial-fibrillat',
  'Consider transcatheter mitral valve intervention evaluation for high-risk MR patient': 'slug:consider-transcatheter-mitral-valve-intervention-evaluation-for-high-r',
  'Consider urgent vascular evaluation for critical limb ischemia with tissue loss': 'slug:consider-urgent-vascular-evaluation-for-critical-limb-ischemia-with-ti',
  'Consider valve-in-valve TAVR evaluation for symptomatic bioprosthetic valve dysfunction': 'gap-sh-valve-in-valve',
  'Consider venous insufficiency evaluation and management for symptomatic varicose veins': 'gap-pv-varicose',
  'DOAC contraindicated in moderate-severe mitral stenosis': 'gap-ep-008-doac-mitral-stenosis',
  'DOAC detected in mechanical valve patient -- contraindicated': 'gap-vd-6-doac-mechanical-valve',
  'DOAC dose not adjusted for renal function (rivaroxaban)': 'gap-ep-003-rivaroxaban-renal-dose',
  'Dental prophylaxis antibiotic recommended for review in prosthetic valve patient': 'gap-vd-14-dental-prophylaxis',
  'Diabetes above glycemic target in heart failure': 'gap-hf-081-dm-hba1c',
  'Digoxin toxicity risk': 'slug:digoxin-toxicity-risk',
  'Diuretic resistance assessment recommended in HF with persistent congestion': 'gap-hf-77-diuretic-resistance',
  'Dofetilide REMS monitoring recommended for review': 'gap-ep-dofetilide-rems',
  'Duplex ultrasound follow-up recommended for review post-intervention': 'slug:duplex-ultrasound-follow-up-recommended-for-review-post-intervention',
  'Ebstein anomaly without arrhythmia surveillance on file': 'gap-sh-099-ebstein-arrhythmia',
  'Echo surveillance overdue for aortic stenosis': 'gap-sh-1-as-surveillance',
  'Echo surveillance overdue for bioprosthetic valve': 'slug:echo-surveillance-overdue-for-bioprosthetic-valve',
  'Echo surveillance overdue for mitral stenosis': 'gap-vd-4-mitral-stenosis',
  'Edoxaban reduced efficacy at high CrCl': 'gap-ep-009-edoxaban-high-crcl',
  'Eisenmenger physiology without PAH-specific therapy evaluation': 'gap-sh-101-eisenmenger-pah',
  'Elevated apolipoprotein B (>=90 mg/dL) on statin: residual atherogenic risk gap': 'gap-cad-009-apob',
  'Endocarditis education documentation recommended for review': 'slug:endocarditis-education-documentation-recommended-for-review',
  'Endocarditis prophylaxis review recommended': 'slug:endocarditis-prophylaxis-review-recommended',
  'Ergot-derived dopamine agonist therapy: drug-induced valve disease surveillance echo gap': 'gap-vhd-091-dopamine-agonist-valve-surveillance',
  'Evidence-based beta-blocker not prescribed in HFrEF': 'gap-hf-35-beta-blocker',
  'Exercise testing recommended for review in asymptomatic severe valve disease': 'slug:exercise-testing-recommended-for-review-in-asymptomatic-severe-valve-d',
  'Fabry disease screening recommended for review in unexplained LVH': 'gap-hf-89-fabry',
  'Fabry disease without disease-modifying therapy': 'gap-hf-061-fabry-ert',
  'Finerenone not prescribed (CKD + T2DM)': 'slug:finerenone-not-prescribed-ckd-t2dm',
  'Full CIED system extraction not performed for device infection': 'gap-ep-034-cied-infection-extraction',
  'Functional iron deficiency untreated in heart failure': 'gap-hf-034-iron-functional',
  'GLP-1 RA not prescribed in HFpEF with obesity': 'gap-hf-7-glp1ra',
  'Giant cell arteritis without glucocorticoid therapy: vision-threatening treatment gap': 'gap-pv-040-gca-steroid',
  'Group-1 PAH without ERA + PDE5i combination therapy': 'gap-pv-084-pah-combination',
  'HCM evaluation recommended for review': 'gap-hf-12-hcm-screening',
  'HF + chronic AF with uncontrolled ventricular rate': 'gap-hf-078-af-rate',
  'HFrEF beta-blocker below target dose with uptitration headroom': 'gap-hf-003-bb-target-dose',
  'HbA1c above target (>=7.0%) in PAD with diabetes: glycemic optimization gap': 'gap-pv-6-diabetes-control',
  'HbA1c monitoring recommended for review in CAD patient with diabetes': 'slug:hba1c-monitoring-recommended-for-review-in-cad-patient-with-diabetes',
  'Heart failure with untreated thyroid dysfunction': 'gap-hf-080-thyroid',
  'Hemodynamically significant ASD: closure evaluation gap': 'gap-sh-asd-closure',
  'Hemolysis monitoring recommended for review in prosthetic valve with anemia': 'slug:hemolysis-monitoring-recommended-for-review-in-prosthetic-valve-with-a',
  'Hydralazine-ISDN not prescribed in self-identified Black patient with HFrEF': 'gap-hf-19-hydralazine-isdn',
  'INR monitoring overdue for mechanical valve on warfarin': 'slug:inr-monitoring-overdue-for-mechanical-valve-on-warfarin',
  'Infective endocarditis with an embolic / uncontrolled-infection surgery indication: surgery evaluation gap': 'gap-sh-029-ie-early-surgery',
  'Infective endocarditis with embolic event on therapy: surgery consideration gap': 'gap-vhd-059-ie-embolic-surgery',
  'Infective endocarditis with heart failure: urgent surgery indication gap': 'gap-vhd-057-ie-hf-surgery',
  'Infective endocarditis with large mobile vegetation (>10 mm): early-surgery consideration gap': 'gap-vhd-060-ie-large-vegetation',
  'Inotrope dependence - advanced heart failure referral': 'gap-hf-047-inotrope-dependence',
  'Inotrope-refractory cardiogenic shock without mechanical circulatory support': 'gap-hf-133-cs-mcs-escalation',
  'Iron deficiency untreated in HF with LVEF ≤45%': 'slug:iron-deficiency-untreated-in-hf-with-lvef-45',
  'Iron studies overdue in anemic heart failure': 'gap-hf-032-iron-screen',
  'Ivabradine not prescribed in HFrEF with elevated HR on max beta-blocker': 'gap-hf-17-ivabradine',
  'LAAC evaluation for high stroke risk with prior major bleed': 'gap-ep-012-laac-high-risk-bleed',
  'LDL not at goal on statin - intensify lipid therapy': 'gap-cad-lipid-intensification',
  'LVAD referral recommended for review in refractory advanced HF': 'slug:lvad-referral-recommended-for-review-in-refractory-advanced-hf',
  'LVEF measurement required to safely guide AF rate-control therapy in HF patient': 'slug:lvef-measurement-required-to-safely-guide-af-rate-control-therapy-in-h',
  'Left atrial appendage assessment recommended for review': 'slug:left-atrial-appendage-assessment-recommended-for-review',
  'Loop diuretic without MRA in HFrEF': 'slug:loop-diuretic-without-mra-in-hfref',
  'Low-flow low-gradient AS: dobutamine stress echo not performed': 'gap-sh-003-lflg-classical',
  'MRA not prescribed in HFrEF with LVEF<=40%': 'gap-hf-36-mra',
  'Marfan with aortic dilation not on beta-blocker or ARB (aortic-growth prophylaxis)': 'gap-sh-052-marfan-bb-arb',
  'Massive (high-risk) PE with instability: reperfusion evaluation gap': 'gap-sh-091-massive-pe-reperfusion',
  'Mechanical prosthetic valve with elevated gradient: thrombosis (PVT) workup gap': 'gap-vhd-068-mech-pvt-gradient',
  'Mechanical valve in a reproductive-age patient: pre-conception anticoagulation counseling gap': 'gap-vhd-098-mech-valve-preconception',
  'Mechanical valve in pregnancy on LMWH: anti-Xa out of therapeutic range (0.8-1.2 U/mL) dose adjustment gap': 'gap-vhd-100-mech-valve-pregnancy-antixa',
  'Mechanical valve in pregnancy: anticoagulation strategy SAFETY review (teratogenicity vs valve-thrombosis tradeoff)': 'gap-vhd-099-mech-valve-pregnancy-anticoag',
  'Mechanical valve with atherosclerotic disease without low-dose ASA adjunct': 'gap-vhd-006-mech-asa-adjunct',
  'Mechanical valve with sub-therapeutic INR: warfarin management gap': 'gap-vhd-001-subtherapeutic-inr',
  'Mixed / multi-valve disease without integrated severity staging': 'gap-vhd-104-mixed-valve-staging',
  'Moderate AS: severity-grading surveillance / integrated clarification': 'gap-sh-050-moderate-as-grading',
  'Moderate MR by color Doppler without quantitative (EROA/vena-contracta) triangulation': 'gap-vhd-105-mr-quant-triangulation',
  'NT-proBNP/BNP monitoring not documented in HF': 'slug:nt-probnp-bnp-monitoring-not-documented-in-hf',
  'Non-compressible ABI (>1.40): toe-brachial index recommended for perfusion assessment': 'gap-pv-004-noncompressible-abi',
  'Non-evidence-based beta-blocker in HFrEF': 'gap-hf-002-bb-non-ebm',
  'Obstructive sleep apnea screening not documented in HF with obesity': 'gap-hf-26-osa-screening',
  'Oral anticoagulant not prescribed in AFib': 'gap-ep-oac-afib',
  'Oral anticoagulant not prescribed in atrial flutter': 'slug:oral-anticoagulant-not-prescribed-in-atrial-flutter',
  'Oral anticoagulation missing in AF with valve disease': 'gap-vd-12-af-valve-anticoag',
  'Orthostatic hypotension on BP-lowering therapy: medication review': 'gap-ep-097-orthostatic-hypotension-med-review',
  'P2Y12 inhibitor not active post-stent/CAD': 'slug:p2y12-inhibitor-not-active-post-stent-cad',
  'PAH on background combination therapy without sotatercept add-on (STELLAR)': 'gap-pv-085-pah-sotatercept',
  'PFO + cryptogenic stroke (age<60): closure evaluation gap': 'gap-sh-026-pfo-cryptogenic-closure',
  'Pacemaker not implanted for Class I bradycardia indication': 'gap-ep-029-pacemaker-class1',
  'Palliative care consult not documented in advanced HF': 'gap-hf-76-palliative-care',
  'Paradoxical low-flow low-gradient AS: stroke-volume/flow assessment needed': 'gap-sh-004-lflg-paradoxical',
  'Paravalvular leak assessment recommended for review post-valve replacement': 'gap-sh-13-paravalvular-leak',
  'Peripartum cardiomyopathy screening recommended for review': 'gap-hf-87-peripartum',
  'Polyvascular disease (3 territories): comprehensive intensified secondary-prevention gap': 'gap-cad-026-polyvascular',
  'Possible tachycardia-mediated cardiomyopathy without rate/rhythm control': 'gap-hf-065-tachy-cm',
  'Post-AVR high-grade AV block: permanent pacing decision gap': 'gap-sh-060-postavr-pacing',
  'Post-AVR new LBBB without ambulatory rhythm monitoring': 'gap-sh-057-postavr-lbbb',
  'Post-AVR on dual antiplatelet: antithrombotic regimen reassessment gap': 'gap-sh-059-postavr-antithrombotic',
  'Post-CABG cardiac rehabilitation referral not documented': 'gap-cad-rehab-cabg',
  'Post-LAAC patient not on any antithrombotic therapy': 'gap-ep-067-post-laac-antithrombotic',
  'Post-LVAD GI bleeding without anti-angiodysplasia therapy': 'gap-hf-148-lvad-gib',
  'Post-MI cardiac rehabilitation referral not documented': 'gap-cad-rehab-mi',
  'Post-MI with LVEF <=35%: primary-prevention ICD evaluation gap': 'gap-cad-022-post-mi-icd',
  'Post-PE persistent dyspnea: CTEPH surveillance workup gap': 'gap-sh-092-cteph-surveillance',
  'Post-TAVR follow-up recommended for review': 'gap-sh-6-post-tavr-followup',
  'Post-heart-transplant CAV surveillance overdue': 'gap-hf-151-transplant-cav',
  'Post-heart-transplant rejection-surveillance biopsy not documented': 'gap-hf-152-transplant-biopsy',
  'Post-mitral-TEER without annual surveillance echo': 'gap-sh-065-postteer-echo',
  'Post-septal-closure device without an antithrombotic regimen': 'gap-sh-082-postclosure-antithrombotic',
  'Post-septal-closure without surveillance echo (residual-shunt assessment)': 'gap-sh-083-postclosure-surveillance',
  'Pregnancy risk assessment recommended for review in valve disease': 'slug:pregnancy-risk-assessment-recommended-for-review-in-valve-disease',
  'Primary-prevention ICD eligibility (ischemic cardiomyopathy)': 'gap-hf-024-icd-primary-ischemic',
  'Primary-prevention ICD eligibility (non-ischemic cardiomyopathy)': 'gap-hf-025-icd-primary-nicm',
  'Prior infective endocarditis: dental antibiotic prophylaxis gap': 'gap-vhd-064-prior-ie-dental-prophylaxis',
  'Prior thoracic radiation with cardiac disease - surveillance echo overdue': 'gap-hf-073-radiation-surv',
  'Radiation-induced coronary disease: aggressive risk-factor modification + surveillance gap': 'gap-cad-083-radiation-cad',
  'Recurrent significant MR after mitral TEER: heart-team reassessment gap': 'gap-sh-066-recurrent-mr-teer',
  'Redo AF ablation evaluation after recurrence': 'gap-ep-072-redo-af-ablation',
  'Remote patient monitoring not documented in high-risk HF': 'gap-hf-29-remote-monitoring',
  'Renal artery stenosis screening recommended for review in PAD with HTN and renal impairment': 'gap-pv-12-renal-artery',
  'Rheumatic heart disease + atrial fibrillation not on warfarin (DOAC contraindicated)': 'gap-vhd-083-rheumatic-af-warfarin',
  'Rheumatic heart disease screening recommended for review': 'slug:rheumatic-heart-disease-screening-recommended-for-review',
  'Rheumatic heart disease without benzathine penicillin secondary prophylaxis': 'gap-vhd-079-rheumatic-prophylaxis',
  'Rivaroxaban: confirm take-with-food counseling for the >=15 mg dose': 'gap-ep-010-rivaroxaban-food',
  'S-ICD not considered for young primary-prevention ICD candidate without pacing need': 'gap-ep-092-sicd-candidate',
  'SAFETY: Dabigatran contraindicated in severe renal impairment (eGFR<30)': 'slug:safety-dabigatran-contraindicated-in-severe-renal-impairment-egfr-30',
  'SAFETY: MRA contraindicated by hyperkalemia or severe renal impairment': 'gap-hf-008-mra-contra',
  'SAFETY: Non-DHP CCB (diltiazem/verapamil) is contraindicated in HFrEF': 'gap-ep-017-hfref-non-dhp-ccb',
  'SAFETY: Prasugrel contraindicated in patient with prior stroke/TIA': 'gap-cad-016-prasugrel-stroke-safety',
  'SAFETY: class IC antiarrhythmic (flecainide/propafenone) contraindicated in structural heart disease': 'gap-ep-049-class-ic-structural',
  'SAFETY: high-dose digoxin in elderly patient with renal impairment': 'gap-hf-015-digoxin-high-elderly',
  'SAFETY: metformin at reduced eGFR in HF + CKD - renal-dose review': 'gap-hf-082-metformin-renal',
  'SAFETY: post-LVAD INR outside therapeutic range': 'slug:safety-post-lvad-inr-outside-therapeutic-range',
  'SAFETY: teratogenic HF medication in pregnancy': 'gap-hf-086-preg-teratogen',
  'SGLT2i initiation deferred below eGFR floor': 'gap-hf-011-sglt2i-egfr-floor',
  'SGLT2i not prescribed in HFmrEF/HFpEF': 'gap-hf-79-sglt2i-hfpef',
  'SGLT2i not prescribed in HFrEF': 'gap-hf-34-sglt2i',
  'SVT ablation not offered for recurrent SVT on antiarrhythmic': 'gap-ep-076-svt-ablation',
  'Sacubitril/valsartan dose optimization review recommended': 'gap-hf-30-arni-underdosing',
  'Secondary-prevention ICD eligibility (prior VT/VF/cardiac arrest)': 'gap-hf-026-icd-secondary',
  'Severe LDL elevation (>=190): familial hypercholesterolemia evaluation and cascade screening gap': 'slug:severe-ldl-elevation-190-familial-hypercholesterolemia-evaluation-and',
  'Severe TR (no CIED lead): Evoque TTVR (TRISCEND) candidacy for device selection': 'gap-sh-069-evoque-ttvr',
  'Severe TR with CIED lead: device selection requires lead-status + coaptation-gap assessment': 'gap-sh-023-tr-device-lead',
  'Severe TR with RV systolic dysfunction (TAPSE<17 or FAC<35): intervention-timing evaluation gap': 'gap-sh-024-tr-rv-dysfunction',
  'Severe asymptomatic AR with LV dysfunction: surgical evaluation gap': 'gap-vhd-103-severe-ar-surgical',
  'Severe asymptomatic AR with preserved EF and LV dilation (LVESD >50 mm): surgical evaluation gap': 'slug:severe-asymptomatic-ar-with-preserved-ef-and-lv-dilation-lvesd-50-mm-s',
  'Severe hyponatremia in heart failure - management evaluation': 'gap-hf-132-tolvaptan-hyponatremia',
  'Severe symptomatic TR: transcatheter tricuspid (T-TEER/TTVR) evaluation gap': 'gap-sh-022-tricuspid-assessment',
  'Smoking cessation referral recommended for review in PAD': 'gap-pv-4-smoking-cessation',
  'Smoking cessation support recommended for review in CAD patient': 'gap-cad-smoking',
  'Stage B (asymptomatic LV dysfunction) without GDMT initiation': 'gap-hf-076-stage-b',
  'Steroid-dependent recurrent pericarditis without IL-1 inhibitor': 'gap-hf-144-pericarditis-il1',
  'Stimulant-associated coronary disease: substance cessation + beta-blocker-caution SAFETY review': 'gap-cad-085-stimulant-cad',
  'Structural heart imaging follow-up recommended for review': 'slug:structural-heart-imaging-follow-up-recommended-for-review',
  'Supervised exercise therapy recommended for review in PAD with claudication': 'gap-pv-5-exercise-therapy',
  'Surgery not considered for severe primary MR with new atrial fibrillation (Class IIa)': 'slug:surgery-not-considered-for-severe-primary-mr-with-new-atrial-fibrillat',
  'Surgery not considered for severe primary MR with pulmonary hypertension (Class IIa)': 'gap-sh-017-primary-mr-pasp',
  'Surgical referral not documented for severe primary mitral regurgitation': 'gap-sh-3-mitral-intervention',
  'Surveillance echocardiography overdue in valvular heart disease': 'slug:surveillance-echocardiography-overdue-in-valvular-heart-disease',
  'Symptomatic carotid stenosis: urgent revascularization evaluation recommended for review': 'gap-pv-058-symptomatic-carotid-revasc',
  'Symptomatic intracranial stenosis without aggressive medical therapy (antiplatelet + statin)': 'gap-pv-062-intracranial-stenosis-medical',
  'Systemic right ventricle (ccTGA / TGA) without dedicated ACHD-center surveillance': 'gap-sh-097-systemic-rv',
  'Takayasu arteritis without immunosuppressive therapy: disease-control gap': 'gap-pv-038-takayasu-immunosuppression',
  'Takotsubo syndrome without recovery echocardiogram': 'gap-hf-072-takotsubo-echo',
  'Torsades de pointes risk: prolonged QTc with QT-prolonging medication(s)': 'slug:torsades-de-pointes-risk-prolonged-qtc-with-qt-prolonging-medication-s',
  'Transcatheter mitral valve replacement candidacy recommended for review': 'gap-sh-016-primary-mr-af',
  'Turner syndrome without cardiac surveillance on file (echo + aortic imaging)': 'gap-sh-054-turner-surveillance',
  'Uncomplicated type-B aortic dissection not on optimal medical therapy (impulse control)': 'gap-sh-074-typeb-omt',
  'Undiagnosed HFpEF screening recommended for review': 'gap-hf-21-hfpef-screening',
  'Unexplained high-grade AV block under 60 - cardiac sarcoidosis workup': 'gap-hf-062-sarcoid-avblock',
  'VT ablation not considered before amiodarone escalation (VANISH)': 'gap-ep-022-vt-ablation-vanish',
  'VT catheter ablation not offered for ischemic VT on antiarrhythmic': 'gap-ep-020-ischemic-vt-ablation',
  'VT substrate evaluation not pursued in non-ischemic cardiomyopathy': 'gap-ep-021-nicm-vt-substrate',
  'Vascular Ehlers-Danlos not on celiprolol / comprehensive vascular surveillance': 'gap-sh-055-veds-celiprolol',
  'Vasculitis-associated coronary disease: vasculitis-specific coordinated management gap': 'gap-cad-084-vasculitis-cad',
  'Vericiguat not prescribed in worsening HF': 'gap-hf-18-vericiguat',
  'Volume status monitoring recommended for review in HF with elevated BNP': 'slug:volume-status-monitoring-recommended-for-review-in-hf-with-elevated-bn',
  'WATCHMAN device follow-up recommended for review': 'slug:watchman-device-follow-up-recommended-for-review',
  'WCD bridge consideration in early post-MI LV dysfunction': 'gap-hf-127-wcd-bridge',
  'Warfarin not active with mechanical valve': 'slug:warfarin-not-active-with-mechanical-valve',
  'Wound care assessment referral recommended for review in PAD': 'slug:wound-care-assessment-referral-recommended-for-review-in-pad',
  'eGFR measurement required to evaluate dabigatran safety in renal impairment': 'slug:egfr-measurement-required-to-evaluate-dabigatran-safety-in-renal-impai',
});

/**
 * Hand-verified patterns for the 10 families whose STORED status carries interpolated values
 * (template literals) or varies by branch (ternaries), so exact match cannot attribute them.
 * Order matters: first match wins. Each maps to the frozen id of its own push site.
 */
export interface PatternAttribution {
  readonly test: RegExp;
  readonly ruleId: string;
  readonly note: string;
}

export const PATTERN_ATTRIBUTIONS: ReadonlyArray<PatternAttribution> = Object.freeze([
  { test: /^Hyponatremia detected: sodium /, ruleId: 'slug:hf-hyponatremia-monitoring', note: 'template: interpolated sodium value' },
  { test: /^QTc (CRITICAL|HIGH)/, ruleId: 'gap-39-qtc-safety', note: 'template: interpolated severity, value and threshold' },
  { test: /^High-intensity statin not prescribed in CAD/, ruleId: 'gap-cad-statin', note: 'ternary: dose-qualified branch' },
  { test: /statin not prescribed in PAD/, ruleId: 'gap-pv-1-pad-statin', note: 'ternary: dose-qualified PAD branch' },
  { test: /^Rate control agent not prescribed in AFib/, ruleId: 'slug:ep-rate-control-afib', note: 'ternary: HFrEF-qualified branch' },
  { test: /transcatheter (edge-to-edge )?repair/, ruleId: 'gap-sh-10-mitraclip', note: 'ternary: secondary-MR TEER branch' },
  { test: /^Ascending aorta at the .* intervention threshold/, ruleId: 'slug:sh-ascending-aorta-intervention-threshold', note: 'template: interpolated subgroup' },
  { test: /^Dronedarone contraindicated in /, ruleId: 'gap-ep-dronedarone', note: 'template: interpolated arm' },
  { test: /^Consider anemia workup for HF patient with hemoglobin </, ruleId: 'gap-hf-anemia-hf', note: 'template: interpolated threshold' },
  { test: /^HFrEF GDMT substantially incomplete \(/, ruleId: 'gap-hf-036-gdmt-incomplete', note: 'template: interpolated pillar count' },
]);
